if &compatible
  set nocompatible
endif
let s:dein_dir = expand('~/src/github.com/Shougo/dein.vim')
let s:plugin_dir = expand('~/.vim/plugins')
set runtimepath+=~/src/github.com/Shougo/dein.vim
if dein#load_state(s:plugin_dir)
  call dein#begin(s:plugin_dir)

  call dein#add(s:dein_dir)

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax on

set directory=/tmp
set fenc=utf-8
set nobackup
set autoread
set hidden
set showcmd
set number
set relativenumber
set cursorline
set cursorcolumn
hi CursorLine   cterm=NONE ctermbg=242 guibg=darkred guifg=white
hi CursorColumn cterm=NONE ctermbg=242 guibg=darkred guifg=white
set virtualedit=onemore
set smartindent
set visualbell
set showmatch
set laststatus=2
set wildmode=list:longest

nnoremap j gj
nnoremap k gk

augroup vimrc-auto-cursorline
  autocmd!
  autocmd CursorMoved,CursorMovedI,WinLeave * setlocal nocursorline nocursorcolumn
  autocmd CursorHold,CursorHoldI * setlocal cursorline cursorcolumn
augroup END
