syntax on

set directory=/tmp
set fenc=utf-8
set nobackup
set noswapfile
set autoread
set hidden
set showcmd
set number
set relativenumber
set cursorline
set cursorcolumn
set virtualedit=onemore
set smartindent
set visualbell
set showmatch
set laststatus=2
set wildmode=list:longest

nnoremap j gj
nnoremap k gk
