syntax on

set directory=/tmp
set fenc=utf-8
set nobackup
set autoread
set hidden
set showcmd
set number
set relativenumber
set cursorline
set cursorcolumn
hi CursorLine   cterm=NONE ctermbg=242 guibg=darkred guifg=white
hi CursorColumn cterm=NONE ctermbg=242 guibg=darkred guifg=white
set virtualedit=onemore
set smartindent
set visualbell
set showmatch
set laststatus=2
set wildmode=list:longest

nnoremap j gj
nnoremap k gk

augroup vimrc-auto-cursorline
  autocmd!
  autocmd CursorMoved,CursorMovedI,WinLeave * setlocal nocursorline
  autocmd CursorHold,CursorHoldI * setlocal cursorline
augroup END
